In [1]:


# # Numpy Introduction
# ## numpy arrays

import numpy as np

# Creating a 1-D array
arr = np.array([1, 3, 4, 5, 6])
print(arr)

# Checking the shape and data type of the array
print(arr.shape)
print(arr.dtype)

# Creating an array with mixed data types
arr = np.array([1, 'st', 'er', 3])
print(arr.dtype)

# Summing the array (will raise an error due to mixed types)
try:
    print(np.sum(arr))
except TypeError as e:
    print(e)

# ### Creating arrays
arr = np.array([[1, 2, 3], [2, 4, 6], [8, 8, 8]])
print(arr.shape)
print(arr)

# Creating arrays of zeros, ones, identity, and random numbers
arr = np.zeros((2, 4))
print(arr)

arr = np.ones((2, 4))
print(arr)

arr = np.identity(3)
print(arr)

arr = np.random.randn(3, 4)
print(arr)

# Reading data from a string buffer
from io import BytesIO
b = BytesIO(b"2,23,33\n32,42,63.4\n35,77,12")
arr = np.genfromtxt(b, delimiter=",")
print(arr)

# ### Accessing array elements
# #### Simple indexing
print(arr[1])

# Creating and reshaping an array
arr = np.arange(12).reshape(2, 2, 3)
print(arr)
print(arr[0])

# Slicing the array
arr = np.arange(10)
print(arr[5:])
print(arr[5:8])
print(arr[:-5])

arr = np.arange(12).reshape(2, 2, 3)
print(arr)
print(arr[1:2])

arr = np.arange(27).reshape(3, 3, 3)
print(arr)
print(arr[:, :, 2])
print(arr[..., 2])

# #### Advanced Indexing
arr = np.arange(9).reshape(3, 3)
print(arr)
print(arr[[0, 1, 2], [1, 0, 0]])

# ##### Boolean Indexing
cities = np.array(["delhi", "bangalore", "mumbai", "chennai", "bhopal"])
city_data = np.random.randn(5, 3)
print(city_data)
print(city_data[cities == "delhi"])
print(city_data[city_data > 0])
city_data[city_data > 0] = 0
print(city_data)

# #### Operations on arrays
arr = np.arange(15).reshape(3, 5)
print(arr)
print(arr + 5)
print(arr * 2)

# Broadcasting example
arr1 = np.arange(15).reshape(5, 3)
arr2 = np.arange(5).reshape(5, 1)
print(arr1)
print(arr2)
print(arr2 + arr1)

# Element-wise operations
arr1 = np.random.randn(5, 3)
print(arr1)
print(np.modf(arr1))

# #### Linear algebra using numpy
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [1, 2, 3]])
print(A.dot(B))

A = np.arange(15).reshape(3, 5)
print(A.T)
print(np.linalg.svd(A))

a = np.array([[7, 5, -3], [3, -5, 2], [5, 3, -7]])
b = np.array([16, -8, 0])
x = np.linalg.solve(a, b)
print(x)
print(np.allclose(np.dot(a, x), b))

# # Pandas
# ## Data frames

import pandas as pd
d = [{'city': 'Delhi', "data": 1000},
     {'city': 'Bangalore', "data": 2000},
     {'city': 'Mumbai', "data": 1000}]
df = pd.DataFrame(d)
print(df)

# ### Reading in data
city_data = pd.read_csv(filepath_or_buffer='simplemaps-worldcities-basic.csv')
print(city_data.head(n=10))
print(city_data.tail())

series_es = city_data.lat
print(type(series_es))
print(series_es[1:10:2])
print(series_es[:7])
print(series_es[:-7315])
print(city_data[:7])
print(city_data.iloc[:5, :4])

city_greater_10mil = city_data[city_data['pop'] > 10000000]
city_greater_10mil.rename(columns={'pop': 'population'}, inplace=True)
print(city_greater_10mil.where(city_greater_10mil.population > 15000000))

df = pd.DataFrame(np.random.randn(8, 3), columns=['A', 'B', 'C'])
print(df.values)
df.iloc[4, 2] = np.nan
print(df)
print(df.fillna(0))

columns_numeric = ['lat', 'lng', 'pop']
print(city_data[columns_numeric].mean())
print(city_data[columns_numeric].sum())
print(city_data[columns_numeric].count())
print(city_data[columns_numeric].median())
print(city_data[columns_numeric].quantile(0.8))
print(city_data[columns_numeric].sum(axis=1).head())
print(city_data[columns_numeric].describe())

city_data1 = city_data.sample(3)
city_data2 = city_data.sample(3)
city_data_combine = pd.concat([city_data1, city_data2])
print(city_data_combine)

df1 = pd.DataFrame({'col1': ['col10', 'col11', 'col12', 'col13'],
                    'col2': ['col20', 'col21', 'col22', 'col23'],
                    'col3': ['col30', 'col31', 'col32', 'col33'],
                    'col4': ['col40', 'col41', 'col42', 'col43']},
                   index=[0, 1, 2, 3])
print(df1)

df4 = pd.DataFrame({'col2': ['col22', 'col23', 'col26', 'col27'],
                    'Col4': ['Col42', 'Col43', 'Col46', 'Col47'],
                    'col6': ['col62', 'col63', 'col66', 'col67']},
                   index=[2, 3, 6, 7])
print(pd.concat([df1, df4], axis=1))

country_data = city_data[['iso3', 'country']].drop_duplicates()
print(country_data.shape)
print(country_data.head())

del city_data['country']
print(city_data.merge(country_data, 'inner').head())

# # Scikit-learn

from sklearn import datasets
diabetes = datasets.load_diabetes()
X = diabetes.data[:10]
y = diabetes.target
print(X[:5])
print(y[:10])

# ## Scikit example regression
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

diabetes = datasets.load_diabetes()
X_train = diabetes.data[:310]
y_train = diabetes.target[:310]

X_test = diabetes.data[310:]
y_test = diabetes.target[310:]

lasso = Lasso(random_state=0)
alphas = np.logspace(-4, -0.5, 30)

estimator = GridSearchCV(lasso, param_grid=dict(alpha=alphas))
estimator.fit(X_train, y_train)

print(estimator.best_score_)
print(estimator.best_estimator_)
print(estimator.predict(X_test))

# ## Deep Learning Frameworks

# ### Theano example 
import theano.tensor as T
from theano import function

x = T.dscalar('x')
y = T.dscalar('y')
z = x + y

f = function([x, y], z)
print(f(8, 2))

# ### Tensorflow example
import tensorflow as tf

hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

# ### Building a neural network model with Keras
from sklearn.datasets import load_breast_cancer
from keras.models import Sequential
from keras.layers import Dense, Dropout

cancer = load_breast_cancer()

X_train = cancer.data[:340]
y_train = cancer.target[:340]

X_test = cancer.data[340:]
y_test = cancer.target[340:]

model = Sequential()
model.add(Dense(15, input_dim=30, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=20, batch_size=50)

predictions = model.predict_classes(X_test)

from sklearn import metrics

print('Accuracy:', metrics.accuracy_score(y_true=y_test, y_pred=predictions))
print(metrics.classification_report(y_true=y_test, y_pred=predictions))

# ### The power of deep learning models
model = Sequential()
model.add(Dense(15, input_dim=30, activation='relu'))
model.add(Dense(15, activation='relu'))
model.add(Dense(15, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=20, batch_size=50)

predictions = model.predict_classes(X_test)

print('Accuracy:', metrics.accuracy_score(y_true=y_test, y_pred=predictions))
print(metrics.classification_report(y_true=y_test, y_pred=predictions))

[1 3 4 5 6]
(5,)
int32
<U11
ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> None
(3, 3)
[[1 2 3]
 [2 4 6]
 [8 8 8]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.30350891  0.00739411  1.79921158  0.02767476]
 [-1.51160379 -0.00325587 -1.29241368  0.68851874]
 [ 0.51909242 -0.01609646  0.6505724  -1.50184529]]
[[ 2.  23.  33. ]
 [32.  42.  63.4]
 [35.  77.  12. ]]
[32.  42.  63.4]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[0 1 2]
 [3 4 5]]
[5 6 7 8 9]
[5 6 7]
[0 1 2 3 4]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 3 6]
[[-0.22380098 -2.04299191 -0.00360294]
 [-0.05688469 -1.71863616 -0.17777861]
 [ 0.36228096 -1.5987203  -0.29075711]
 [-2.30493426  0.3498336   0.12372406]
 [-0.24895599  2.53508937  1.47542192]]
[[-0.22380098 -2.04299191 -0.00360294]]
[0.36228096 0.3498336  0.12372406 2.53508937 1.47542192]
[[-0.22380098 -2.04299191 -0.00360294]
 [-0.05688469 -1.71863616 -0.17777861]
 [ 0.         -1.5987203  -0.29075711]
 [-2.30493426  0.          0.        ]
 [-0.24895599  0.          0.        ]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]]
[[-0.3050634  -1.17261879 -0.82714019]
 [-0.62364102  0.86019673 -1.75526664]
 [-0.51934505  1.09748077  0.51432575]
 [-0.69591794  0.10859939  1.1513394 ]
 [ 0.07707335  0.25359835  0.04593547]]
(array([[-0.3050634 , -0.17261879, -0.82714019],
       [-0.62364102,  0.86019673, -0.75526664],
       [-0.51934505,  0.09748077,  0.51432575],
       [-0.69591794,  0.10859939,  0.1513394 ],
       [ 0.07707335,  0.25359835,  0.04593547]]), array([[-0., -1., -0.],
       [-0.,  0., -1.],
       [-0.,  1.,  0.],
       [-0.,  0.,  1.],
       [ 0.,  0.,  0.]]))
[[ 24  24  24]
 [ 72  69  66]
 [120 114 108]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
(array([[-0.15425367, -0.89974393,  0.40824829],
       [-0.50248417, -0.28432901, -0.81649658],
       [-0.85071468,  0.3310859 ,  0.40824829]]), array([3.17420265e+01, 2.72832424e+00, 9.19513106e-16]), array([[-0.34716018, -0.39465093, -0.44214167, -0.48963242, -0.53712316],
       [ 0.69244481,  0.37980343,  0.06716206, -0.24547932, -0.55812069],
       [ 0.45650723, -0.61153491,  0.23629065, -0.46400549,  0.38274252],
       [-0.2754905 , -0.21468338,  0.83080946,  0.08439319, -0.42502878],
       [-0.34015605,  0.52908988,  0.23221189, -0.69106924,  0.26992351]]))
[1. 3. 2.]
True
        city  data
0      Delhi  1000
1  Bangalore  2000
2     Mumbai  1000
             city      city_ascii        lat        lng       pop  \
0   Qal eh-ye Now       Qal eh-ye  34.983000  63.133300    2997.0
1     Chaghcharan     Chaghcharan  34.516701  65.250001   15000.0
2     Lashkar Gah     Lashkar Gah  31.582998  64.360000  201546.0
3          Zaranj          Zaranj  31.112001  61.886998   49851.0
4      Tarin Kowt      Tarin Kowt  32.633298  65.866699   10000.0
5    Zareh Sharan    Zareh Sharan  32.850000  68.416705   13737.0
6        Asadabad        Asadabad  34.866000  71.150005   48400.0
7         Taloqan         Taloqan  36.729999  69.540004   64256.0
8  Mahmud-E Eraqi  Mahmud-E Eraqi  35.016696  69.333301    7407.0
9      Mehtar Lam      Mehtar Lam  34.650000  70.166701   17345.0

       country iso2 iso3 province
0  Afghanistan   AF  AFG  Badghis
1  Afghanistan   AF  AFG     Ghor
2  Afghanistan   AF  AFG  Hilmand
3  Afghanistan   AF  AFG   Nimroz
4  Afghanistan   AF  AFG  Uruzgan
5  Afghanistan   AF  AFG  Paktika
6  Afghanistan   AF  AFG    Kunar
7  Afghanistan   AF  AFG   Takhar
8  Afghanistan   AF  AFG   Kapisa
9  Afghanistan   AF  AFG  Laghman
             city   city_ascii        lat        lng        pop   country  \
7317       Mutare       Mutare -18.970019  32.650038   216785.0  Zimbabwe
7318       Kadoma       Kadoma -18.330006  29.909947    56400.0  Zimbabwe
7319  Chitungwiza  Chitungwiza -18.000001  31.100003   331071.0  Zimbabwe
7320       Harare       Harare -17.817790  31.044709  1557406.5  Zimbabwe
7321     Bulawayo     Bulawayo -20.169998  28.580002   697096.0  Zimbabwe

     iso2 iso3          province
7317   ZW  ZWE        Manicaland
7318   ZW  ZWE  Mashonaland West
7319   ZW  ZWE            Harare
7320   ZW  ZWE            Harare
7321   ZW  ZWE          Bulawayo
<class 'pandas.core.series.Series'>
1    34.516701
3    31.112001
5    32.850000
7    36.729999
9    34.650000
Name: lat, dtype: float64
0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
Name: lat, dtype: float64
0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
Name: lat, dtype: float64
            city    city_ascii        lat        lng       pop      country  \
0  Qal eh-ye Now     Qal eh-ye  34.983000  63.133300    2997.0  Afghanistan
1    Chaghcharan   Chaghcharan  34.516701  65.250001   15000.0  Afghanistan
2    Lashkar Gah   Lashkar Gah  31.582998  64.360000  201546.0  Afghanistan
3         Zaranj        Zaranj  31.112001  61.886998   49851.0  Afghanistan
4     Tarin Kowt    Tarin Kowt  32.633298  65.866699   10000.0  Afghanistan
5   Zareh Sharan  Zareh Sharan  32.850000  68.416705   13737.0  Afghanistan
6       Asadabad      Asadabad  34.866000  71.150005   48400.0  Afghanistan

  iso2 iso3 province
0   AF  AFG  Badghis
1   AF  AFG     Ghor
2   AF  AFG  Hilmand
3   AF  AFG   Nimroz
4   AF  AFG  Uruzgan
5   AF  AFG  Paktika
6   AF  AFG    Kunar
            city   city_ascii        lat        lng
0  Qal eh-ye Now    Qal eh-ye  34.983000  63.133300
1    Chaghcharan  Chaghcharan  34.516701  65.250001
2    Lashkar Gah  Lashkar Gah  31.582998  64.360000
3         Zaranj       Zaranj  31.112001  61.886998
4     Tarin Kowt   Tarin Kowt  32.633298  65.866699
        city city_ascii        lat         lng  population country iso2 iso3  \
360      NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN
1171     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN
2068     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN
3098     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN
3110  Mumbai     Mumbai  19.016990   72.856989  15834918.0   India   IN  IND
3492   Tokyo      Tokyo  35.685017  139.751407  22006299.5   Japan   JP  JPN
4074     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN
4513     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN
5394     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN
6124     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN
7071     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN

         province
360           NaN
1171          NaN
2068          NaN
3098          NaN
3110  Maharashtra
3492        Tokyo
4074          NaN
4513          NaN
5394          NaN
6124          NaN
7071          NaN
[[-0.50412393  1.7844854  -1.42965803]
 [-2.10533526  0.29310339 -0.21885021]
 [ 0.73056083  0.36671437  0.15661973]
 [ 1.94034194 -1.40666929 -0.61512625]
 [-1.04139557  1.14817463 -0.97142214]
 [-1.39159758 -0.45307018  1.26333844]
 [ 0.21970096 -1.0304219  -0.387151  ]
 [ 0.58893753  0.25579861 -0.32683711]]
          A         B         C
0 -0.504124  1.784485 -1.429658
1 -2.105335  0.293103 -0.218850
2  0.730561  0.366714  0.156620
3  1.940342 -1.406669 -0.615126
4 -1.041396  1.148175       NaN
5 -1.391598 -0.453070  1.263338
6  0.219701 -1.030422 -0.387151
7  0.588938  0.255799 -0.326837
          A         B         C
0 -0.504124  1.784485 -1.429658
1 -2.105335  0.293103 -0.218850
2  0.730561  0.366714  0.156620
3  1.940342 -1.406669 -0.615126
4 -1.041396  1.148175  0.000000
5 -1.391598 -0.453070  1.263338
6  0.219701 -1.030422 -0.387151
7  0.588938  0.255799 -0.326837
lat        20.662876
lng        10.711914
pop    265463.071633
dtype: float64
lat    1.512936e+05
lng    7.843263e+04
pop    1.943721e+09
dtype: float64
lat    7322
lng    7322
pop    7322
dtype: int64
lat       26.792730
lng       18.617509
pop    61322.750000
dtype: float64
lat        46.852480
lng        89.900018
pop    269210.000000
Name: 0.8, dtype: float64
0      3095.116300
1     15099.766702
2    201641.942998
3     49943.998999
4     10098.499997
dtype: float64
               lat          lng           pop
count  7322.000000  7322.000000  7.322000e+03
mean     20.662876    10.711914  2.654631e+05
std      29.134818    79.044615  8.287622e+05
min     -89.982894  -179.589979 -9.900000e+01
25%      -0.324710   -64.788472  1.734425e+04
50%      26.792730    18.617509  6.132275e+04
75%      43.575448    73.103628  2.001726e+05
max      82.483323   179.383304  2.200630e+07
               city     city_ascii        lat        lng       pop  \
3882     Nouakchott     Nouakchott  18.086427 -15.975340  701772.0
988          Granja         Granja  -3.119514 -40.839998   17233.0
6806  Traverse City  Traverse City  44.768442 -85.622175   28807.0
6422      Southaven      Southaven  34.968911 -90.003457   79923.0
2828          Catio          Catio  11.216700 -15.166700    9898.0
1391           Wawa           Wawa  48.000415 -84.783337    2174.0

                       country iso2 iso3     province
3882                Mauritania   MR  MRT   Nouakchott
988                     Brazil   BR  BRA        Ceará
6806  United States of America   US  USA     Michigan
6422  United States of America   US  USA  Mississippi
2828             Guinea Bissau   GW  GNB      Tombali
1391                    Canada   CA  CAN      Ontario
    col1   col2   col3   col4
0  col10  col20  col30  col40
1  col11  col21  col31  col41
2  col12  col22  col32  col42
3  col13  col23  col33  col43
    col1   col2   col3   col4   col2   Col4   col6
0  col10  col20  col30  col40    NaN    NaN    NaN
1  col11  col21  col31  col41    NaN    NaN    NaN
2  col12  col22  col32  col42  col22  Col42  col62
3  col13  col23  col33  col43  col23  Col43  col63
6    NaN    NaN    NaN    NaN  col26  Col46  col66
7    NaN    NaN    NaN    NaN  col27  Col47  col67
(223, 2)
    iso3         country
0    AFG     Afghanistan
33   ALD           Aland
34   ALB         Albania
60   DZA         Algeria
111  ASM  American Samoa
            city   city_ascii        lat        lng       pop iso2 iso3  \
0  Qal eh-ye Now    Qal eh-ye  34.983000  63.133300    2997.0   AF  AFG
1    Chaghcharan  Chaghcharan  34.516701  65.250001   15000.0   AF  AFG
2    Lashkar Gah  Lashkar Gah  31.582998  64.360000  201546.0   AF  AFG
3         Zaranj       Zaranj  31.112001  61.886998   49851.0   AF  AFG
4     Tarin Kowt   Tarin Kowt  32.633298  65.866699   10000.0   AF  AFG

  province      country
0  Badghis  Afghanistan
1     Ghor  Afghanistan
2  Hilmand  Afghanistan
3   Nimroz  Afghanistan
4  Uruzgan  Afghanistan

C:\Users\hp\AppData\Local\Temp\ipykernel_14412\3131479420.py:145: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  city_greater_10mil.rename(columns={'pop': 'population'}, inplace=True)

[[ 0.03807591  0.05068012  0.06169621  0.02187239 -0.0442235  -0.03482076
  -0.04340085 -0.00259226  0.01990749 -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 -0.02632753 -0.00844872 -0.01916334
   0.07441156 -0.03949338 -0.06833155 -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 -0.00567042 -0.04559945 -0.03419447
  -0.03235593 -0.00259226  0.00286131 -0.02593034]
 [-0.08906294 -0.04464164 -0.01159501 -0.03665608  0.01219057  0.02499059
  -0.03603757  0.03430886  0.02268774 -0.00936191]
 [ 0.00538306 -0.04464164 -0.03638469  0.02187239  0.00393485  0.01559614
   0.00814208 -0.00259226 -0.03198764 -0.04664087]]
[151.  75. 141. 206. 135.  97. 138.  63. 110. 310.]
0.4617085978039121
Lasso(alpha=0.07880462815669913, random_state=0)
[199.94087733 178.15662017 123.03143905 212.48942817 171.72456577
 118.01035679 201.00001815 170.22184202 163.33982068 183.90802313
 190.88042058 278.2331978  288.52690865 233.65699315 206.83385406
 227.76704035 156.62863347 222.71036088 187.99209072 104.47027841
 169.94419795 110.98568359 282.08739125 176.77611521  80.9375394
  87.75562991 251.78385742 163.64788474 123.67411982 157.33435533
 160.41428724 180.7451196  163.06269765 154.46131367 145.51446622
 130.61629963 188.10921571 108.32911587 128.07205996  90.08120394
 248.91497802  86.45226907  59.61436707 189.70455214 208.04170235
 129.45724924  95.70803064 200.75869738  56.99153436 169.76526312
 190.25007088 120.81554192 227.80666085 157.06775428 158.4251236
 162.676224   259.94948427 259.47887161 204.01189873 182.12509505
  63.63417378 213.62193941 111.77824089 137.49129296 124.16595483
 174.44907373 216.33505211 162.79145    161.82362955 127.16818153
 167.35955169  75.45529901 260.3077748  116.35197225 122.65661021
 132.94689484 109.75931265 100.47872022 158.53346202  85.30903167
 264.87933968  58.6122629  104.29689307 102.60696979 272.04345424
 166.26398887  67.83648837 179.99457719 178.15044556 190.47581936
 175.34426384  92.20398717 143.27416212 253.80593232 192.59990509
 267.96596302  53.83906654 179.13200812 195.48469539 168.38026021
 163.88067972 155.18701801 227.51355145 126.36688669 172.2853051
 168.62823018 217.9462074  157.43804452 108.58046263  82.58886016
 136.96335023 189.6939806  205.9282737  143.45531749 168.97632157
 109.3806794  161.47462457 129.404664   258.71876333 106.18129318
 115.84744998 118.96077334 224.00885051  65.7887307  135.56387541
 120.42653096  57.21529849 190.34881031 112.70450409 121.77218172
 209.03211476  59.59945496]

ModuleNotFoundError: No module named 'theano'